#!/usr/bin/env python3
"""deviations.py -- generate notes/DEVIATIONS.md from git (R5).

Every place this tree departs from the sources it came from, and why,
taken from git rather than kept by hand:

  OSFMK   compared with mkunity-master/osfmk/src in mach_stuff, at the
          commit CI pins -- the pristine baseline, which differed from
          the original reference tree only in the project's own edits
          (G149)
  LITES   compared with its pristine vendor import, the commit
          "lites: vendor LITES 1.1.u3 in as a server of the tree"

Files are compared by git blob hash, so nothing is extracted, and the
sparse mach_stuff checkout that CI uses is enough. The reason for each
file is the list of commits that changed it, by author date and
subject -- not hash, because a commit re-created with git am keeps its
subject and author date but gets a new hash.

Usage, from anywhere in the repository:

  python3 tools/deviations.py            rewrite notes/DEVIATIONS.md
  python3 tools/deviations.py --check    exit 1 if it is out of date

MACH_STUFF names the mach_stuff clone (default ~/mach_stuff).

The record describes committed history, so a commit that changes a vendor
file leaves it stale. Regenerate after committing and fold it in:

  git commit ...; python3 tools/deviations.py
  git add notes/DEVIATIONS.md; git commit --amend --no-edit

which is safe because the record names commits by date and subject, and
an amend keeps both.
"""

import os
import subprocess
import sys

MACH_STUFF = os.environ.get('MACH_STUFF', os.path.expanduser('~/mach_stuff'))
MACH_STUFF_PIN = '78cab0993cbfd2f55b3f1d818e42c6a0f7875bdf'  # as in .github/workflows/ci.yml
OSFMK_BASE = 'mkunity-master/osfmk/src/'
OSFMK = 'osfmk/src/'
LITES = 'osfmk/src/mach_services/servers/lites/'
LITES_IMPORT_SUBJECT = 'lites: vendor LITES 1.1.u3 in as a server of the tree'
OUT = 'notes/DEVIATIONS.md'


def git(*args, cwd=None):
    return subprocess.run(['git', *args], cwd=cwd, check=True,
                          capture_output=True, text=True).stdout


def blobs(ref, prefix, cwd=None):
    """{path relative to prefix: blob hash} for the files under prefix."""
    out = {}
    for line in git('ls-tree', '-r', '-z', ref, '--', prefix, cwd=cwd).split('\0'):
        if not line:
            continue
        meta, path = line.split('\t', 1)
        mode, kind, sha = meta.split()
        if kind == 'blob':
            out[path[len(prefix):]] = sha
    return out


def commits(path, since=None):
    """The commits that changed path, oldest first, as 'date subject'."""
    rng = [f'{since}..HEAD'] if since else []
    root = git('rev-list', '--max-parents=0', 'HEAD').split()
    log = git('log', '--reverse', '--date=short', '--format=%H %ad %s', *rng, '--', path)
    rows = []
    for line in log.splitlines():
        sha, date, subject = line.split(' ', 2)
        if sha in root:
            continue
        rows.append(f'{date} {subject.replace("|", "/")}')
    return rows


def table(title, paths, prefix, since=None):
    lines = [f'### {title} ({len(paths)})', '']
    if not paths:
        return lines + ['None.', '']
    lines += ['| file | commits that changed it |', '|---|---|']
    for p in paths:
        why = commits(prefix + p, since) or ['*no commit since the baseline*']
        lines.append(f'| `{p}` | ' + '<br>'.join(why) + ' |')
    return lines + ['']


def generate():
    top = git('rev-parse', '--show-toplevel').strip()
    os.chdir(top)
    base = blobs(MACH_STUFF_PIN, OSFMK_BASE, cwd=MACH_STUFF)
    tree = {p: s for p, s in blobs('HEAD', OSFMK).items()
            if not (OSFMK + p).startswith(LITES)}
    o_mod = sorted(p for p in tree if p in base and tree[p] != base[p])
    o_new = sorted(p for p in tree if p not in base)
    o_gone = sorted(p for p in base if p not in tree)

    imp = git('log', '--format=%H', '--fixed-strings',
              f'--grep={LITES_IMPORT_SUBJECT}', 'HEAD').split()
    if len(imp) != 1:
        sys.exit(f'deviations: expected one LITES import commit, found {len(imp)}')
    imp = imp[0]
    l_base, l_tree = blobs(imp, LITES), blobs('HEAD', LITES)
    l_mod = sorted(p for p in l_tree if p in l_base and l_tree[p] != l_base[p])
    l_new = sorted(p for p in l_tree if p not in l_base)
    l_gone = sorted(p for p in l_base if p not in l_tree)

    out = [
        '# Deviations from the vendor sources',
        '',
        '*Generated by `tools/deviations.py` from git -- do not edit by hand;',
        'regenerate it, and check it with `--check`.*',
        '',
        'Every file that differs from the sources this tree came from, and',
        'the commits that made it differ. A file is **modified** when it',
        'exists in the baseline with different contents, **new** when the',
        'baseline does not have it, **removed** when only the baseline does.',
        '',
        '| part | baseline | modified | new | removed |',
        '|---|---|---|---|---|',
        f'| OSFMK (`{OSFMK}`, without LITES) | `{OSFMK_BASE}` in mach_stuff at `{MACH_STUFF_PIN[:12]}` (G149) | {len(o_mod)} | {len(o_new)} | {len(o_gone)} |',
        f'| LITES (`{LITES}`) | its vendor import, "{LITES_IMPORT_SUBJECT}" | {len(l_mod)} | {len(l_new)} | {len(l_gone)} |',
        '',
        '## OSFMK',
        '',
        *table('Modified vendor files', o_mod, OSFMK),
        *table('New files', o_new, OSFMK),
        *table('Removed files', o_gone, OSFMK),
        '## LITES',
        '',
        *table('Modified vendor files', l_mod, LITES, since=imp),
        *table('New files', l_new, LITES, since=imp),
        *table('Removed files', l_gone, LITES, since=imp),
    ]
    return '\n'.join(out).rstrip('\n') + '\n'


def main():
    text = generate()
    if sys.argv[1:] == ['--check']:
        cur = open(OUT).read() if os.path.exists(OUT) else ''
        if cur != text:
            print(f'deviations: {OUT} is out of date; run python3 tools/deviations.py')
            sys.exit(1)
        print(f'deviations: {OUT} is up to date')
        return
    if sys.argv[1:]:
        sys.exit(__doc__)
    open(OUT, 'w').write(text)
    print(f'deviations: wrote {OUT}')


if __name__ == '__main__':
    main()
